#!/usr/bin/python


def login(username,password):
    '''
    用于用户登陆
    :param username: 用户名
    :param password:密码
    :return:True 表示登陆成功 ， false表示登陆失败
    '''
    f = open("db",'r')
    for line in f:
        li=line.split("|")
        if li[0] == username and li[1] == password:
            return  True
    return False


def register(username,password):
    '''
    注册
    :param username: 用户名
    :param password:密码
    :return:  默认返回值none
    '''
    f = open("db",'a')
    temp = username + '|' + password
    f.write(temp)
    f.close()


def  main():
    t = input("1:登陆；2：注册")
    if t == '1':
        username=input("请输入用户名：")
        password = input("请输入密码：")
        r=login(username,password)
        if r :
            print("登陆成功")
        else:
            print("用户名或密码错误")
    else:
        username = input("请输入用户名：")
        password = input("请输入密码：")
        register(username,password)


main()




